version: 2 # CircleCI version
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/vision_search # Default working directory, 
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage test
    