version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'working directory is, '
      - run: pwd
      - run: pip install -r requirements.txt
      - run: python manage test
    