version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          echo 'working directory is, '
          pwd
          pip install -r requirements.txt
          python manage.py test
    