version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python model_extraction.py
      - run: python manage.py test
    