version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.0
    working_directory: ~/.ssh/vision_search
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python manage test
    